'use strict';
const DB_NAME='inventory-manager-v2';
const DB_VERSION=1;
const STORE='app';
const STATE_KEY='state';
const BACKUPS_KEY='backups';
const LEGACY_KEY='inventory-manager-v1';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
let state={items:[],settings:{theme:'system'},bulkDefaults:{weight:'',cost:''}};
let visibleItems=[];
let photoDraft='';
let backupTimer;
let lastSnapshotAt=0;
let bulkTarget='form';
let importMode='replace';

function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function n(v){const x=parseFloat(v);return Number.isFinite(x)?x:0}
function text(v){return String(v??'')}
function esc(v){return text(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dateLabel(v){if(!v)return 'No date';const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString()}
function profitOf(x){return n(x.sold)-n(x.cost)}
function marginOf(x){return n(x.sold)?profitOf(x)/n(x.sold):0}
function normalizeItem(x={}){return {id:x.id||uid(),name:text(x.name||x['Item Name']),size:text(x.size||x.Size),category:text(x.category||x.Category),weight:valueOrBlank(x.weight??x['Weight (oz)']??x.Weight),cost:valueOrBlank(x.cost??x.Cost),sold:valueOrBlank(x.sold??x.Sold),purchaseDate:text(x.purchaseDate||x['Purchase Date']),source:text(x.source||x['Purchased From']),location:text(x.location||x['Storage Location']),notes:text(x.notes||x.Notes),photo:text(x.photo),createdAt:x.createdAt||Date.now(),updatedAt:x.updatedAt||Date.now()}}
function valueOrBlank(v){return v===''||v===null||v===undefined?'':n(v)}

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbGet(key){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbSet(key,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function loadState(){let saved=await dbGet(STATE_KEY);if(saved?.items){state=saved;state.items=state.items.map(normalizeItem);return}try{const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY));if(Array.isArray(legacy)){state.items=legacy.map(normalizeItem);localStorage.removeItem(LEGACY_KEY)}}catch{}await persist(false)}
async function persist(snapshot=true){await dbSet(STATE_KEY,state);if(snapshot)scheduleSnapshot()}
function scheduleSnapshot(){clearTimeout(backupTimer);backupTimer=setTimeout(createAutomaticSnapshot,1800)}
async function createAutomaticSnapshot(force=false){const now=Date.now();if(!force&&now-lastSnapshotAt<5*60*1000)return;const backups=(await dbGet(BACKUPS_KEY))||[];const signature=JSON.stringify(state.items.map(x=>[x.id,x.updatedAt,x.sold,x.cost]));if(backups[0]?.signature===signature)return;backups.unshift({id:uid(),createdAt:now,signature,label:'Automatic snapshot',state:structuredClone(state)});await dbSet(BACKUPS_KEY,backups.slice(0,10));lastSnapshotAt=now}

function applyTheme(){const preferred=state.settings?.theme||'system';const dark=preferred==='dark'||(preferred==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';$('#themeBtn').textContent=dark?'☀':'◐'}
async function toggleTheme(){const dark=document.documentElement.dataset.theme==='dark';state.settings.theme=dark?'light':'dark';applyTheme();await persist(false)}

function getFilters(){return {q:$('#search').value.trim().toLowerCase(),status:$('#statusFilter').value,category:$('#categoryFilter').value,sort:$('#sortBy').value}}
function updateCategoryOptions(){const current=$('#categoryFilter').value;const cats=[...new Set(state.items.map(x=>x.category.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));$('#categoryFilter').innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(cats.includes(current))$('#categoryFilter').value=current}
function filteredItems(){const f=getFilters();let rows=state.items.filter(x=>{const hay=[x.name,x.size,x.category,x.location,x.source,x.notes].join(' ').toLowerCase();const statusOk=f.status==='all'||(f.status==='sold'?n(x.sold)>0:n(x.sold)===0);const catOk=f.category==='all'||x.category===f.category;return (!f.q||hay.includes(f.q))&&statusOk&&catOk});rows=[...rows];if(f.sort==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));if(f.sort==='costHigh')rows.sort((a,b)=>n(b.cost)-n(a.cost));if(f.sort==='profitHigh')rows.sort((a,b)=>profitOf(b)-profitOf(a));if(f.sort==='newest')rows.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));return rows}
function render(){updateCategoryOptions();visibleItems=filteredItems();renderMetrics();renderDesktop();renderMobile();$('#resultCount').textContent=`${visibleItems.length} of ${state.items.length} items`;$('#emptyState').classList.toggle('hidden',visibleItems.length>0);$('#desktopTable').classList.toggle('hidden',visibleItems.length===0);$('#mobileCards').classList.toggle('hidden',visibleItems.length===0)}
function renderMetrics(){const totalCost=state.items.reduce((s,x)=>s+n(x.cost),0);const totalSold=state.items.reduce((s,x)=>s+n(x.sold),0);const profit=totalSold-totalCost;const margin=totalSold?profit/totalSold:0;const unsold=state.items.filter(x=>!n(x.sold)).length;$('#metricItems').textContent=state.items.length;$('#metricUnsold').textContent=`${unsold} unsold`;$('#metricCost').textContent=money.format(totalCost);$('#metricSold').textContent=money.format(totalSold);$('#metricProfit').textContent=money.format(profit);$('#metricProfit').className=profit<0?'negative':'positive';$('#metricMargin').textContent=`${(margin*100).toFixed(2)}% margin`}
function photoHTML(x,cls='thumb'){return x.photo?`<img class="${cls}" src="${x.photo}" alt="${esc(x.name)}">`:`<div class="${cls} thumb-placeholder" aria-hidden="true">👕</div>`}
function renderDesktop(){$('#tableBody').innerHTML=visibleItems.map(x=>{const p=profitOf(x);return `<tr><td>${photoHTML(x)}</td><td><div class="item-title">${esc(x.name||'Untitled item')}</div><div class="item-meta">${esc(x.category||'Uncategorized')}</div></td><td><div>${esc(x.size||'—')} · ${x.weight!==''?esc(x.weight)+' oz':'No weight'}</div><div class="item-meta">${esc(x.location||x.source||dateLabel(x.purchaseDate))}</div></td><td class="money">${money.format(n(x.cost))}</td><td class="money">${n(x.sold)?money.format(n(x.sold)):'—'}</td><td class="money ${p<0?'negative':'positive'}">${money.format(p)}<div class="item-meta">${(marginOf(x)*100).toFixed(1)}%</div></td><td><div class="row-actions"><button data-action="edit" data-id="${x.id}">Edit</button><button data-action="delete" data-id="${x.id}" aria-label="Delete">×</button></div></td></tr>`}).join('')}
function renderMobile(){$('#mobileCards').innerHTML=visibleItems.map(x=>{const p=profitOf(x);return `<article class="inventory-card"><div class="card-top">${photoHTML(x,'thumb card-photo')}<div class="card-main"><h3>${esc(x.name||'Untitled item')}</h3><div class="badges">${x.size?`<span class="badge">${esc(x.size)}</span>`:''}${x.category?`<span class="badge">${esc(x.category)}</span>`:''}${x.location?`<span class="badge">${esc(x.location)}</span>`:''}</div><div class="item-meta">${x.weight!==''?esc(x.weight)+' oz':'No weight'} · ${x.purchaseDate?dateLabel(x.purchaseDate):'No purchase date'}</div></div></div><div class="card-money"><div><span>Cost</span><strong>${money.format(n(x.cost))}</strong></div><div><span>Sold</span><strong>${n(x.sold)?money.format(n(x.sold)):'—'}</strong></div><div><span>Profit</span><strong class="${p<0?'negative':'positive'}">${money.format(p)}</strong></div></div><div class="card-actions"><button data-action="edit" data-id="${x.id}">Edit Item</button><button data-action="delete" data-id="${x.id}">Remove</button></div></article>`}).join('')}

function openItem(id=''){const item=id?state.items.find(x=>x.id===id):normalizeItem({purchaseDate:new Date().toISOString().slice(0,10)});$('#itemDialogTitle').textContent=id?'Edit Item':'Add Item';$('#editId').value=id;$('#fName').value=item.name;$('#fSize').value=item.size;$('#fCategory').value=item.category;$('#fWeight').value=item.weight;$('#fCost').value=item.cost;$('#fSold').value=item.sold;$('#fDate').value=item.purchaseDate;$('#fSource').value=item.source;$('#fLocation').value=item.location;$('#fNotes').value=item.notes;photoDraft=item.photo;refreshPhotoPreview();$('#itemDialog').showModal();setTimeout(()=>$('#fName').focus(),50)}
function refreshPhotoPreview(){$('#photoPreview').src=photoDraft||'';$('#photoPreview').classList.toggle('hidden',!photoDraft);$('#photoPlaceholder').classList.toggle('hidden',!!photoDraft);$('#removePhotoBtn').classList.toggle('hidden',!photoDraft)}
async function saveItem(e){e.preventDefault();const id=$('#editId').value;const existing=id?state.items.find(x=>x.id===id):null;const item=normalizeItem({id:id||uid(),name:$('#fName').value.trim(),size:$('#fSize').value.trim(),category:$('#fCategory').value.trim(),weight:$('#fWeight').value,cost:$('#fCost').value,sold:$('#fSold').value,purchaseDate:$('#fDate').value,source:$('#fSource').value.trim(),location:$('#fLocation').value.trim(),notes:$('#fNotes').value.trim(),photo:photoDraft,createdAt:existing?.createdAt||Date.now(),updatedAt:Date.now()});if(existing)Object.assign(existing,item);else state.items.unshift(item);await persist();$('#itemDialog').close();render();toast(existing?'Item updated':'Item added')}
async function removeItem(id){const item=state.items.find(x=>x.id===id);if(!item||!confirm(`Remove "${item.name||'this item'}"?`))return;await createAutomaticSnapshot(true);state.items=state.items.filter(x=>x.id!==id);await persist(false);render();toast('Item removed')}
function handleAction(e){const btn=e.target.closest('[data-action]');if(!btn)return;if(btn.dataset.action==='edit')openItem(btn.dataset.id);if(btn.dataset.action==='delete')removeItem(btn.dataset.id)}

async function compressImage(file){const bitmap=await createImageBitmap(file);const max=900;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.76)}
async function choosePhoto(e){const file=e.target.files?.[0];if(!file)return;try{photoDraft=await compressImage(file);refreshPhotoPreview();toast('Photo ready')}catch{alert('The photo could not be processed.')}e.target.value=''}

function openBulk(target='form'){bulkTarget=target;$('#bulkWeight').value=state.bulkDefaults.weight??'';$('#bulkCost').value=state.bulkDefaults.cost??'';$('#bulkItemWeight').value=target==='form'?$('#fWeight').value:'';calcBulk();$('#bulkDialog').showModal()}
function calcBulk(){const w=n($('#bulkWeight').value),c=n($('#bulkCost').value),iw=n($('#bulkItemWeight').value);const per=w?c/w:0;const item=per*(iw/16);$('#bulkPerLb').textContent=money.format(per);$('#bulkItemCost').textContent=money.format(item);return item}
async function applyBulk(){const w=n($('#bulkWeight').value),c=n($('#bulkCost').value),iw=n($('#bulkItemWeight').value);if(!(w>0&&iw>0)){alert('Enter a bulk weight and item weight greater than zero.');return}const cost=calcBulk();state.bulkDefaults={weight:w,cost:c};await persist(false);if(bulkTarget==='form'){$('#fWeight').value=iw;$('#fCost').value=cost.toFixed(2);toast('Cost applied to item')}else toast(`Saved bulk rate: ${money.format(c/w)} per lb`);$('#bulkDialog').close()}

function csvEscape(v){return `"${text(v).replace(/"/g,'""')}"`}
function exportRows(){return state.items.map(x=>({'Item Name':x.name,'Size':x.size,'Category':x.category,'Weight (oz)':x.weight,'Cost':x.cost,'Sold':x.sold,'Profit':profitOf(x),'Profit Margin':marginOf(x),'Purchase Date':x.purchaseDate,'Purchased From':x.source,'Storage Location':x.location,'Notes':x.notes}))}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCSV(){const rows=exportRows();const headers=Object.keys(rows[0]||{'Item Name':'','Size':'','Category':'','Weight (oz)':'','Cost':'','Sold':''});const csv=[headers.map(csvEscape).join(','),...rows.map(r=>headers.map(h=>csvEscape(r[h])).join(','))].join('\r\n');download(`inventory-${today()}.csv`,csv,'text/csv;charset=utf-8');toast('CSV exported')}
function exportJSON(){download(`inventory-backup-${today()}.json`,JSON.stringify({version:2,exportedAt:new Date().toISOString(),state},null,2),'application/json');toast('Backup exported')}
function exportXLSX(){if(!window.XLSX){alert('Excel tools are still loading. Check your connection and try again.');return}const rows=exportRows();const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:34},{wch:10},{wch:16},{wch:12},{wch:12},{wch:12},{wch:12},{wch:14},{wch:15},{wch:20},{wch:20},{wch:34}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Inventory');XLSX.writeFile(wb,`inventory-${today()}.xlsx`);toast('Excel workbook exported')}
function today(){return new Date().toISOString().slice(0,10)}

function parseCSV(str){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<str.length;i++){const ch=str[i],next=str[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++}else if(ch==='"'){quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(v=>v!==''))rows.push(row);if(!rows.length)return[];const headers=rows.shift().map(h=>h.trim());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
async function parseImportFile(file){const ext=file.name.split('.').pop().toLowerCase();if(ext==='json'){const obj=JSON.parse(await file.text());const arr=Array.isArray(obj)?obj:obj.state?.items;if(!Array.isArray(arr))throw Error('No inventory items were found.');return arr.map(normalizeItem)}if(ext==='csv')return parseCSV(await file.text()).map(normalizeItem);if(['xlsx','xls'].includes(ext)){if(!window.XLSX)throw Error('Excel tools are unavailable. Connect to the internet once and reopen the app.');const data=await file.arrayBuffer();const wb=XLSX.read(data);const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});return rows.map(normalizeItem)}throw Error('Choose a CSV, Excel, or JSON file.')}
async function importFile(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const incoming=await parseImportFile(file);if(!incoming.length)throw Error('The file did not contain any inventory rows.');await createAutomaticSnapshot(true);state.items=importMode==='append'?[...incoming,...state.items]:incoming;await persist(false);render();toast(`${incoming.length} items imported`)}catch(err){alert(err.message||'The file could not be imported.')}}

function openIODialog(type){$('#ioTitle').textContent=type==='import'?'Import Inventory':'Export Inventory';if(type==='import'){$('#ioBody').innerHTML=`<div class="io-options"><button data-io="replace"><strong>Replace current inventory</strong><span>Creates a recovery snapshot, then loads the selected CSV, Excel, or JSON file.</span></button><button data-io="append"><strong>Add to current inventory</strong><span>Imports rows without removing existing items.</span></button></div>`}else{$('#ioBody').innerHTML=`<div class="io-options"><button data-io="csv"><strong>Export CSV</strong><span>Universal spreadsheet format.</span></button><button data-io="xlsx"><strong>Export Excel (.xlsx)</strong><span>Formatted workbook for Microsoft Excel.</span></button><button data-io="json"><strong>Export full backup</strong><span>Best format for restoring all app data.</span></button></div>`}$('#ioDialog').showModal()}
async function handleIO(e){const action=e.target.closest('[data-io]')?.dataset.io;if(!action)return;$('#ioDialog').close();if(action==='replace'||action==='append'){importMode=action;$('#importFile').click()}if(action==='csv')exportCSV();if(action==='xlsx')exportXLSX();if(action==='json')exportJSON()}

async function showBackups(){const backups=(await dbGet(BACKUPS_KEY))||[];$('#backupList').innerHTML=backups.length?backups.map(b=>`<div class="backup-entry"><div><strong>${new Date(b.createdAt).toLocaleString()}</strong><small>${b.state.items.length} items · ${esc(b.label)}</small></div><div><button data-restore="${b.id}">Restore</button><button data-download-backup="${b.id}">Download</button></div></div>`).join(''):'<div class="empty"><h3>No snapshots yet</h3><p>A snapshot is created automatically after changes.</p></div>';$('#backupDialog').showModal()}
async function handleBackupAction(e){const restore=e.target.closest('[data-restore]')?.dataset.restore;const dl=e.target.closest('[data-download-backup]')?.dataset.downloadBackup;if(!restore&&!dl)return;const backups=(await dbGet(BACKUPS_KEY))||[];const b=backups.find(x=>x.id===(restore||dl));if(!b)return;if(dl){download(`inventory-snapshot-${new Date(b.createdAt).toISOString().replace(/[:.]/g,'-')}.json`,JSON.stringify({version:2,state:b.state},null,2),'application/json');return}if(confirm('Restore this snapshot and replace the current inventory?')){await createAutomaticSnapshot(true);state=structuredClone(b.state);await persist(false);applyTheme();render();$('#backupDialog').close();toast('Snapshot restored')}}
async function shareBackup(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const file=new File([blob],`inventory-backup-${today()}.json`,{type:'application/json'});if(navigator.canShare?.({files:[file]})){await navigator.share({title:'Inventory backup',text:'Inventory Manager backup',files:[file]})}else exportJSON()}

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)}
function debounce(fn,delay=150){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),delay)}}
function closeByData(e){const id=e.target.closest('[data-close]')?.dataset.close;if(id)$('#'+id).close()}

async function init(){await loadState();state.settings=state.settings||{theme:'system'};state.bulkDefaults=state.bulkDefaults||{weight:'',cost:''};applyTheme();render();const isIOS=/iphone|ipad|ipod/i.test(navigator.userAgent);const standalone=matchMedia('(display-mode:standalone)').matches||navigator.standalone===true;if(isIOS&&!standalone)$('#installHint').classList.remove('hidden');if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
  $('#addBtn').onclick=()=>openItem();$('#mobileAdd').onclick=()=>openItem();$('#themeBtn').onclick=toggleTheme;$('#itemForm').addEventListener('submit',saveItem);$('#desktopTable').addEventListener('click',handleAction);$('#mobileCards').addEventListener('click',handleAction);$('#photoButton').onclick=()=>$('#photoInput').click();$('#photoInput').addEventListener('change',choosePhoto);$('#removePhotoBtn').onclick=()=>{photoDraft='';refreshPhotoPreview()};$('#itemBulkBtn').onclick=()=>openBulk('form');$('#bulkBatchBtn').onclick=()=>openBulk('defaults');['bulkWeight','bulkCost','bulkItemWeight'].forEach(id=>$('#'+id).addEventListener('input',calcBulk));$('#applyBulk').onclick=applyBulk;
  const rerender=debounce(render);$('#search').addEventListener('input',rerender);['statusFilter','categoryFilter','sortBy'].forEach(id=>$('#'+id).addEventListener('change',render));$('#importBtn').onclick=()=>openIODialog('import');$('#exportBtn').onclick=()=>openIODialog('export');$('#ioBody').addEventListener('click',handleIO);$('#importFile').addEventListener('change',importFile);$('#backupBtn').onclick=showBackups;$('#mobileBackup').onclick=shareBackup;$('#shareBackupBtn').onclick=shareBackup;$('#backupList').addEventListener('click',handleBackupAction);$('#printBtn').onclick=()=>print();$('#mobileSearch').onclick=()=>{$('#search').focus();$('#search').scrollIntoView({behavior:'smooth',block:'center'})};$('#mobileDashboard').onclick=()=>scrollTo({top:0,behavior:'smooth'});document.addEventListener('click',closeByData);matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(state.settings.theme==='system')applyTheme()});
}
init().catch(err=>{console.error(err);alert('Inventory Manager could not start. Please reload the app.')});
